## DAN AHIMBISIBWE - da3658 - HOMEWORK2 -WEEK2 - Numpy and Pandas

In [3]:
import numpy as np
import pandas as pd

# NUMPY

### 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.vstack((a,b))

d = np.hstack((a,b))
print(f"Vertical Stacking:\n {c}")
print(f"Horizontal Stacking: \n{d}")

Vertical Stacking:
 [[1 2 3]
 [4 5 6]]
Horizontal Stacking: 
[1 2 3 4 5 6]


### 2. Find common elements between A and B. [Hint : Intersection of two sets]

In [7]:

A = np.array([2, 4, 6, 8, 10])
B = np.array([4, 8, 12, 16])

C = np.intersect1d(A, B)
print(f"Common Elements between A and B are: {C}")


Common Elements between A and B are: [4 8]


### 3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [11]:
a = np.arange(11)

c = np.where((a >= 5) & (a <= 10))

print(f"Extracted Numbers: {a[c]}")


Extracted Numbers: [ 5  6  7  8  9 10]


### 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [11]:



url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d


a = iris_2d[(iris_2d[:,2]>1.5) & (iris_2d[:,0] < 5.0)]
print(a)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


# PANDAS

### 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [15]:


df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.head()

df1 = ["Manufacturer", "Model", "Type"]
df_filter = df.loc[::20, df1]

df_filter

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

### 2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [16]:

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head()

df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())
df[['Min.Price', 'Max.Price']]


Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]

### 3. How to get the rows of a dataframe with row sum > 100?

In [17]:

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

filtered_rows = df[df.sum(axis=1) > 100]
print(filtered_rows)

     0   1   2   3
3   38  21  16  26
6   16  34  18  35
10  29  32  30  30
11  29  28  37  38
12  34  25  29  36
